version: "3.9"
services:
  backend:
    build: ../backend
    container_name: k-sasa-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - K_SASA_SEED_DIR=/data/seed
      - K_SASA_AUDIT_DIR=/var/audit
      - K_SASA_STATIC_DIR=/app/static
    env_file:
      - ../.env
    depends_on:
      - minio
    networks:
      - ksasa-net
    volumes:
      - ../data:/data:ro
      - backend-audit:/var/audit
      - backend-static:/app/static
  minio:
    image: minio/minio:RELEASE.2024-07-26T18-04-17Z
    container_name: k-sasa-minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - ksasa-net
  frontend:
    build: ../frontend
    container_name: k-sasa-frontend
    ports:
      - "5173:5173"
    networks:
      - ksasa-net
    depends_on:
      - backend

networks:
  ksasa-net:
    driver: bridge

volumes:
  minio-data:
    driver: local
  backend-audit:
    driver: local
  backend-static:
    driver: local
